Signup and Login functionalities for project Canteen Koala
flaviuvr/canteen-koala pull request #2
Opened 2021-05-10 11:09 UTC by flaviuvr

Changes in this PR: 

- Added Users model
- Added Signup and Login functionalities
- Added new views for the necessary forms and for user details

2021-05-11 09:09 UTC, VictorMotogna commented on app/assets/stylesheets/main_page.scss
> +}
you should add a newline at the end of this file

2021-05-11 09:09 UTC, VictorMotogna commented on app/models/user.rb
> +  validates :email, presence: true, length: { maximum: 255 }, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
nice 👍

2021-05-11 10:45 UTC, VictorMotogna approved these changes

2021-05-11 11:43 UTC, vaneaclaudia approved these changes

2021-05-13 08:30 UTC, AdrianFlorian requested changes
nice job @flaviuvr ! 👏 just a few comments :-)

2021-05-13 08:30 UTC, AdrianFlorian commented on app/helpers/sessions_helper.rb
> +      @current_user ||= User.find_by(id: session[:user_id])
you can do this in a one-liner :-)

2021-05-13 08:30 UTC, AdrianFlorian commented on app/views/main_page/home.html.haml
> +          .page-button= link_to 'Home', '#'
it's a better practice to put the class on a separate line, like:

```
.page-button
  = link_to 'Home', '#'
```

Can you update this everywhere? :-)

2021-05-13 08:30 UTC, AdrianFlorian commented on app/views/main_page/home.html.haml
> +        %a.add-card{:href => new_product_path}
why not use `link_to`?

2021-05-13 08:30 UTC, AdrianFlorian commented on app/views/main_page/landing.html.haml
> +    .button.explore-btn= link_to 'Explore Products', main_page_home_path
it's a good practice to group the logic by using new lines, it will make the code easier to read :-)

2021-05-13 08:30 UTC, AdrianFlorian commented on app/views/sessions/new.html.haml
> +      .field
group then by using a new line :-)

2021-05-13 08:30 UTC, AdrianFlorian commented on app/views/users/new.html.haml
> +        = form.submit
same here, group with newline, to increase readability :-)

2021-05-13 08:30 UTC, AdrianFlorian commented on test/controllers/sessions_controller_test.rb
> +  test "should get new" do
why not use rspec?

2021-05-13 08:30 UTC, AdrianFlorian commented on test/models/user_test.rb
> +
delete if not used :-)

2021-05-14 09:48 UTC, AdrianFlorian approved these changes
@flaviuvr nice job 👏

2021-05-14 09:49 UTC, AdrianFlorian commented
@flaviuvr pare ca nu merge pagina de sign-up https://safe-sierra-95488.herokuapp.com/signup

2021-05-14 09:55 UTC, flaviuvr commented
> @flaviuvr pare ca nu merge pagina de sign-up https://safe-sierra-95488.herokuapp.com/signup

@AdrianFlorian well this is awkward. Incearca acum, ar trebui sa mearga

2021-05-14 09:56 UTC, AdrianFlorian commented
merge, super, merci!

*Confidential:* The information in this email shall not be made public. All
the information is sensitive and is therefore protected due to its economic
value (contract clauses, prices, costs etc). This email may also contain
aspects that Wolfpack Digital SRL must protect according to the governing
legislation or according to contracts signed with business partners.
Disclosing, using or destroying the information is limited to authorised
users. Users are granted rights over this document solely under the
protection of a confidentiality clause.

Wolfpack Digital is an ISO 9001:2015 and ISO 27001:2013 certified company.

[image: Wolfpack Digital graphic element]

Adrian Florian

CTO

+40752 821 508 <+40752+821+508>

www.wolfpack-digital.com

[image: Wolfpack Digital Facebook profile]
<https://www.facebook.com/wolfpackdigital/> [image: Wolfpack Digital
Linkedin profile] <https://www.linkedin.com/company/wolfpack-digital/> [image:
Wolfpack Digital Instagram profile]
<https://www.instagram.com/wolfpack.digital/> [image: Wolfpack Digital
Twitter profile] <https://twitter.com/DigitalWolfpack> [image: Wolfpack
Digital Medium profile] <https://medium.com/wolfpack-digital> [image:
Wolfpack Digital Dribbble profile] <https://dribbble.com/wolfpack-digital>
[image: Wolf illustration]


On Fri, May 14, 2021 at 12:55 PM Flaviu Raita ***@***.***>
wrote:

> @flaviuvr <https://github.com/flaviuvr> pare ca nu merge pagina de
> sign-up https://safe-sierra-95488.herokuapp.com/signup
>
> @AdrianFlorian <https://github.com/AdrianFlorian> well this is awkward.
> Incearca acum, ar trebui sa mearga
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/flaviuvr/canteen-koala/pull/2#issuecomment-841142103>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHWQXIK4J3VS2HGPQMHEKTTNTXRNANCNFSM44Q5IGBQ>
> .
>

2021-05-18 10:47 UTC, merged